# Generated by Django 3.0.5 on 2020-08-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vs_trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='serv_desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
